image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add util-linux pciutils usbutils coreutils binutils findutils grep
  - apk add --no-cache curl jq python3 py3-pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)


stages:
  - build

Docker-Build:
  stage: build
  script:
    - echo $REPO_URL:$IMAGE_TAG
    - docker build -t my-service .
    - docker images
    - docker tag my-service:latest 407759171288.dkr.ecr.eu-west-1.amazonaws.com/my-service:latest
    - docker push 407759171288.dkr.ecr.eu-west-1.amazonaws.com/my-service:latest
  only:
    - master